---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/MyMavenWebApp-CICD/target/my-maven-app.war"
        dest: "/opt/tomcat/webapps/my-maven-app.war"
        remote_src: no

    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
